// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetUserRequest, GetUserResponse} from "./user_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserService
 */
export declare const UserService: {
  readonly typeName: "user.v1.UserService",
  readonly methods: {
    /**
     * @generated from rpc user.v1.UserService.GetUser
     */
    readonly getUser: {
      readonly name: "GetUser",
      readonly I: typeof GetUserRequest,
      readonly O: typeof GetUserResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

