// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/genres/v1/genre.proto (package music.genres.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListGenresRequest, ListGenresResponse} from "./genre_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.genres.v1.GenresService
 */
export declare const GenresService: {
  readonly typeName: "music.genres.v1.GenresService",
  readonly methods: {
    /**
     * @generated from rpc music.genres.v1.GenresService.ListGenres
     */
    readonly listGenres: {
      readonly name: "ListGenres",
      readonly I: typeof ListGenresRequest,
      readonly O: typeof ListGenresResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

