// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/genres/v1/genre.proto (package music.genres.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message music.genres.v1.Genre
 */
export const Genre = proto3.makeMessageType(
  "music.genres.v1.Genre",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message music.genres.v1.ListGenresRequest
 */
export const ListGenresRequest = proto3.makeMessageType(
  "music.genres.v1.ListGenresRequest",
  [],
);

/**
 * @generated from message music.genres.v1.ListGenresResponse
 */
export const ListGenresResponse = proto3.makeMessageType(
  "music.genres.v1.ListGenresResponse",
  () => [
    { no: 1, name: "genres", kind: "message", T: Genre, repeated: true },
  ],
);

