// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/genres/v1/genre.proto (package music.genres.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListGenresRequest, ListGenresResponse} from "./genre_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.genres.v1.GenresService
 */
export const GenresService = {
  typeName: "music.genres.v1.GenresService",
  methods: {
    /**
     * @generated from rpc music.genres.v1.GenresService.ListGenres
     */
    listGenres: {
      name: "ListGenres",
      I: ListGenresRequest,
      O: ListGenresResponse,
      kind: MethodKind.Unary,
    },
  }
};

