// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/genres/v1/genre.proto (package music.genres.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message music.genres.v1.Genre
 */
export declare class Genre extends Message<Genre> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<Genre>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.genres.v1.Genre";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Genre;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Genre;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Genre;

  static equals(a: Genre | PlainMessage<Genre> | undefined, b: Genre | PlainMessage<Genre> | undefined): boolean;
}

/**
 * @generated from message music.genres.v1.ListGenresRequest
 */
export declare class ListGenresRequest extends Message<ListGenresRequest> {
  constructor(data?: PartialMessage<ListGenresRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.genres.v1.ListGenresRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListGenresRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListGenresRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListGenresRequest;

  static equals(a: ListGenresRequest | PlainMessage<ListGenresRequest> | undefined, b: ListGenresRequest | PlainMessage<ListGenresRequest> | undefined): boolean;
}

/**
 * @generated from message music.genres.v1.ListGenresResponse
 */
export declare class ListGenresResponse extends Message<ListGenresResponse> {
  /**
   * @generated from field: repeated music.genres.v1.Genre genres = 1;
   */
  genres: Genre[];

  constructor(data?: PartialMessage<ListGenresResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.genres.v1.ListGenresResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListGenresResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListGenresResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListGenresResponse;

  static equals(a: ListGenresResponse | PlainMessage<ListGenresResponse> | undefined, b: ListGenresResponse | PlainMessage<ListGenresResponse> | undefined): boolean;
}

