// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file reports/v1/report.proto (package reports.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message reports.v1.Report
 */
export declare class Report extends Message<Report> {
  /**
   * @generated from field: bytes report = 1;
   */
  report: Uint8Array;

  constructor(data?: PartialMessage<Report>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "reports.v1.Report";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Report;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Report;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Report;

  static equals(a: Report | PlainMessage<Report> | undefined, b: Report | PlainMessage<Report> | undefined): boolean;
}

/**
 * @generated from message reports.v1.GetReportRequest
 */
export declare class GetReportRequest extends Message<GetReportRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  constructor(data?: PartialMessage<GetReportRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "reports.v1.GetReportRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReportRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReportRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReportRequest;

  static equals(a: GetReportRequest | PlainMessage<GetReportRequest> | undefined, b: GetReportRequest | PlainMessage<GetReportRequest> | undefined): boolean;
}

/**
 * @generated from message reports.v1.GetReportResponse
 */
export declare class GetReportResponse extends Message<GetReportResponse> {
  /**
   * @generated from field: reports.v1.Report report = 1;
   */
  report?: Report;

  constructor(data?: PartialMessage<GetReportResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "reports.v1.GetReportResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetReportResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetReportResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetReportResponse;

  static equals(a: GetReportResponse | PlainMessage<GetReportResponse> | undefined, b: GetReportResponse | PlainMessage<GetReportResponse> | undefined): boolean;
}

