// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file reports/v1/report.proto (package reports.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {GetReportRequest, GetReportResponse} from "./report_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service reports.v1.ReportService
 */
export declare const ReportService: {
  readonly typeName: "reports.v1.ReportService",
  readonly methods: {
    /**
     * @generated from rpc reports.v1.ReportService.GetReport
     */
    readonly getReport: {
      readonly name: "GetReport",
      readonly I: typeof GetReportRequest,
      readonly O: typeof GetReportResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

