// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file reports/v1/report.proto (package reports.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message reports.v1.Report
 */
export const Report = proto3.makeMessageType(
  "reports.v1.Report",
  () => [
    { no: 1, name: "report", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message reports.v1.GetReportRequest
 */
export const GetReportRequest = proto3.makeMessageType(
  "reports.v1.GetReportRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message reports.v1.GetReportResponse
 */
export const GetReportResponse = proto3.makeMessageType(
  "reports.v1.GetReportResponse",
  () => [
    { no: 1, name: "report", kind: "message", T: Report },
  ],
);

