// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: music/artists/v1/artist.proto

package artists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images []*Image `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *Artist) Reset() {
	*x = Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_artists_v1_artist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_music_artists_v1_artist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_music_artists_v1_artist_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  int32  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_artists_v1_artist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_music_artists_v1_artist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_music_artists_v1_artist_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ListArtistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ListArtistsRequest) Reset() {
	*x = ListArtistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_artists_v1_artist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistsRequest) ProtoMessage() {}

func (x *ListArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_artists_v1_artist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistsRequest.ProtoReflect.Descriptor instead.
func (*ListArtistsRequest) Descriptor() ([]byte, []int) {
	return file_music_artists_v1_artist_proto_rawDescGZIP(), []int{2}
}

func (x *ListArtistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListArtistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artists []*Artist `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
}

func (x *ListArtistsResponse) Reset() {
	*x = ListArtistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_music_artists_v1_artist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArtistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtistsResponse) ProtoMessage() {}

func (x *ListArtistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_artists_v1_artist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtistsResponse.ProtoReflect.Descriptor instead.
func (*ListArtistsResponse) Descriptor() ([]byte, []int) {
	return file_music_artists_v1_artist_proto_rawDescGZIP(), []int{3}
}

func (x *ListArtistsResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

var File_music_artists_v1_artist_proto protoreflect.FileDescriptor

var file_music_artists_v1_artist_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x22, 0x5d, 0x0a, 0x06, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2f, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x47, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x49, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x32, 0x6b, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x12, 0x24, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xca, 0x01,
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x69, 0x6b, 0x70, 0x61, 0x75, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x6d, 0x79,
	0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x64, 0x65,
	0x66, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0xa2, 0x02, 0x03, 0x4d, 0x41, 0x58,
	0xaa, 0x02, 0x10, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x5c, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x5c, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x3a, 0x3a, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_music_artists_v1_artist_proto_rawDescOnce sync.Once
	file_music_artists_v1_artist_proto_rawDescData = file_music_artists_v1_artist_proto_rawDesc
)

func file_music_artists_v1_artist_proto_rawDescGZIP() []byte {
	file_music_artists_v1_artist_proto_rawDescOnce.Do(func() {
		file_music_artists_v1_artist_proto_rawDescData = protoimpl.X.CompressGZIP(file_music_artists_v1_artist_proto_rawDescData)
	})
	return file_music_artists_v1_artist_proto_rawDescData
}

var file_music_artists_v1_artist_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_music_artists_v1_artist_proto_goTypes = []interface{}{
	(*Artist)(nil),              // 0: music.artists.v1.Artist
	(*Image)(nil),               // 1: music.artists.v1.Image
	(*ListArtistsRequest)(nil),  // 2: music.artists.v1.ListArtistsRequest
	(*ListArtistsResponse)(nil), // 3: music.artists.v1.ListArtistsResponse
}
var file_music_artists_v1_artist_proto_depIdxs = []int32{
	1, // 0: music.artists.v1.Artist.images:type_name -> music.artists.v1.Image
	0, // 1: music.artists.v1.ListArtistsResponse.artists:type_name -> music.artists.v1.Artist
	2, // 2: music.artists.v1.ArtistService.ListArtists:input_type -> music.artists.v1.ListArtistsRequest
	3, // 3: music.artists.v1.ArtistService.ListArtists:output_type -> music.artists.v1.ListArtistsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_music_artists_v1_artist_proto_init() }
func file_music_artists_v1_artist_proto_init() {
	if File_music_artists_v1_artist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_music_artists_v1_artist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_artists_v1_artist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_artists_v1_artist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArtistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_music_artists_v1_artist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArtistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_music_artists_v1_artist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_music_artists_v1_artist_proto_goTypes,
		DependencyIndexes: file_music_artists_v1_artist_proto_depIdxs,
		MessageInfos:      file_music_artists_v1_artist_proto_msgTypes,
	}.Build()
	File_music_artists_v1_artist_proto = out.File
	file_music_artists_v1_artist_proto_rawDesc = nil
	file_music_artists_v1_artist_proto_goTypes = nil
	file_music_artists_v1_artist_proto_depIdxs = nil
}
