// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/artists/v1/artist.proto (package music.artists.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message music.artists.v1.Artist
 */
export declare class Artist extends Message<Artist> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated music.artists.v1.Image images = 3;
   */
  images: Image[];

  constructor(data?: PartialMessage<Artist>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.artists.v1.Artist";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Artist;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Artist;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Artist;

  static equals(a: Artist | PlainMessage<Artist> | undefined, b: Artist | PlainMessage<Artist> | undefined): boolean;
}

/**
 * @generated from message music.artists.v1.Image
 */
export declare class Image extends Message<Image> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: int32 width = 2;
   */
  width: number;

  /**
   * @generated from field: int32 height = 3;
   */
  height: number;

  constructor(data?: PartialMessage<Image>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.artists.v1.Image";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Image;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Image;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Image;

  static equals(a: Image | PlainMessage<Image> | undefined, b: Image | PlainMessage<Image> | undefined): boolean;
}

/**
 * @generated from message music.artists.v1.ListArtistsRequest
 */
export declare class ListArtistsRequest extends Message<ListArtistsRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  constructor(data?: PartialMessage<ListArtistsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.artists.v1.ListArtistsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtistsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtistsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtistsRequest;

  static equals(a: ListArtistsRequest | PlainMessage<ListArtistsRequest> | undefined, b: ListArtistsRequest | PlainMessage<ListArtistsRequest> | undefined): boolean;
}

/**
 * @generated from message music.artists.v1.ListArtistsResponse
 */
export declare class ListArtistsResponse extends Message<ListArtistsResponse> {
  /**
   * @generated from field: repeated music.artists.v1.Artist artists = 1;
   */
  artists: Artist[];

  constructor(data?: PartialMessage<ListArtistsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.artists.v1.ListArtistsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtistsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtistsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtistsResponse;

  static equals(a: ListArtistsResponse | PlainMessage<ListArtistsResponse> | undefined, b: ListArtistsResponse | PlainMessage<ListArtistsResponse> | undefined): boolean;
}

