// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/artists/v1/artist.proto (package music.artists.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message music.artists.v1.Artist
 */
export const Artist = proto3.makeMessageType(
  "music.artists.v1.Artist",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "images", kind: "message", T: Image, repeated: true },
    { no: 4, name: "counts", kind: "message", T: ArtistCounts },
  ],
);

/**
 * @generated from message music.artists.v1.Image
 */
export const Image = proto3.makeMessageType(
  "music.artists.v1.Image",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "width", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message music.artists.v1.ArtistCounts
 */
export const ArtistCounts = proto3.makeMessageType(
  "music.artists.v1.ArtistCounts",
  () => [
    { no: 1, name: "in_liked_songs", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "in_playlists", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message music.artists.v1.ListArtistsRequest
 */
export const ListArtistsRequest = proto3.makeMessageType(
  "music.artists.v1.ListArtistsRequest",
  () => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message music.artists.v1.ListArtistsResponse
 */
export const ListArtistsResponse = proto3.makeMessageType(
  "music.artists.v1.ListArtistsResponse",
  () => [
    { no: 1, name: "artists", kind: "message", T: Artist, repeated: true },
  ],
);

