// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/artists/v1/artist.proto (package music.artists.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListArtistsRequest, ListArtistsResponse} from "./artist_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.artists.v1.ArtistService
 */
export declare const ArtistService: {
  readonly typeName: "music.artists.v1.ArtistService",
  readonly methods: {
    /**
     * @generated from rpc music.artists.v1.ArtistService.ListArtists
     */
    readonly listArtists: {
      readonly name: "ListArtists",
      readonly I: typeof ListArtistsRequest,
      readonly O: typeof ListArtistsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

