// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/artists/v1/artist.proto (package music.artists.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListArtistsRequest, ListArtistsResponse} from "./artist_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.artists.v1.ArtistService
 */
export const ArtistService = {
  typeName: "music.artists.v1.ArtistService",
  methods: {
    /**
     * @generated from rpc music.artists.v1.ArtistService.ListArtists
     */
    listArtists: {
      name: "ListArtists",
      I: ListArtistsRequest,
      O: ListArtistsResponse,
      kind: MethodKind.Unary,
    },
  }
};

