// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/tracks/v1/history.proto (package music.tracks.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListTrackHistoryRequest, ListTrackHistoryResponse} from "./history_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.tracks.v1.TrackHistoryService
 */
export const TrackHistoryService = {
  typeName: "music.tracks.v1.TrackHistoryService",
  methods: {
    /**
     * @generated from rpc music.tracks.v1.TrackHistoryService.ListTrackHistory
     */
    listTrackHistory: {
      name: "ListTrackHistory",
      I: ListTrackHistoryRequest,
      O: ListTrackHistoryResponse,
      kind: MethodKind.Unary,
    },
  }
};

