// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/tracks/v1/history.proto (package music.tracks.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";
import {Track} from "./track_pb.js";

/**
 * @generated from message music.tracks.v1.TrackHistoryEntry
 */
export const TrackHistoryEntry = proto3.makeMessageType(
  "music.tracks.v1.TrackHistoryEntry",
  () => [
    { no: 1, name: "track", kind: "message", T: Track },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message music.tracks.v1.ListTrackHistoryRequest
 */
export const ListTrackHistoryRequest = proto3.makeMessageType(
  "music.tracks.v1.ListTrackHistoryRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "start", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "end", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message music.tracks.v1.ListTrackHistoryResponse
 */
export const ListTrackHistoryResponse = proto3.makeMessageType(
  "music.tracks.v1.ListTrackHistoryResponse",
  () => [
    { no: 1, name: "entries", kind: "message", T: TrackHistoryEntry, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

