// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/tracks/v1/track.proto (package music.tracks.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message music.tracks.v1.Track
 */
export const Track = proto3.makeMessageType(
  "music.tracks.v1.Track",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "artist_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "bpm", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "genres", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message music.tracks.v1.ListTracksRequest
 */
export const ListTracksRequest = proto3.makeMessageType(
  "music.tracks.v1.ListTracksRequest",
  () => [
    { no: 1, name: "ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message music.tracks.v1.ListTracksResponse
 */
export const ListTracksResponse = proto3.makeMessageType(
  "music.tracks.v1.ListTracksResponse",
  () => [
    { no: 1, name: "tracks", kind: "message", T: Track, repeated: true },
  ],
);

