// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file music/tracks/v1/track.proto (package music.tracks.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ListTracksRequest, ListTracksResponse} from "./track_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service music.tracks.v1.TrackService
 */
export const TrackService = {
  typeName: "music.tracks.v1.TrackService",
  methods: {
    /**
     * @generated from rpc music.tracks.v1.TrackService.ListTracks
     */
    listTracks: {
      name: "ListTracks",
      I: ListTracksRequest,
      O: ListTracksResponse,
      kind: MethodKind.Unary,
    },
  }
};

