// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file music/tracks/v1/track.proto (package music.tracks.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3} from "@bufbuild/protobuf";

/**
 * @generated from message music.tracks.v1.Track
 */
export declare class Track extends Message<Track> {
  /**
   * @generated from field: int64 name = 1;
   */
  name: bigint;

  /**
   * @generated from field: string artist_id = 2;
   */
  artistId: string;

  /**
   * @generated from field: int32 bpm = 3;
   */
  bpm: number;

  /**
   * @generated from field: repeated string genres = 4;
   */
  genres: string[];

  constructor(data?: PartialMessage<Track>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.tracks.v1.Track";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Track;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Track;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Track;

  static equals(a: Track | PlainMessage<Track> | undefined, b: Track | PlainMessage<Track> | undefined): boolean;
}

/**
 * @generated from message music.tracks.v1.ListTracksRequest
 */
export declare class ListTracksRequest extends Message<ListTracksRequest> {
  /**
   * @generated from field: repeated string ids = 1;
   */
  ids: string[];

  constructor(data?: PartialMessage<ListTracksRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.tracks.v1.ListTracksRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTracksRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTracksRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTracksRequest;

  static equals(a: ListTracksRequest | PlainMessage<ListTracksRequest> | undefined, b: ListTracksRequest | PlainMessage<ListTracksRequest> | undefined): boolean;
}

/**
 * @generated from message music.tracks.v1.ListTracksResponse
 */
export declare class ListTracksResponse extends Message<ListTracksResponse> {
  /**
   * @generated from field: repeated music.tracks.v1.Track tracks = 1;
   */
  tracks: Track[];

  constructor(data?: PartialMessage<ListTracksResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "music.tracks.v1.ListTracksResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTracksResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTracksResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTracksResponse;

  static equals(a: ListTracksResponse | PlainMessage<ListTracksResponse> | undefined, b: ListTracksResponse | PlainMessage<ListTracksResponse> | undefined): boolean;
}

