// @generated by protoc-gen-es v0.1.1 with parameter "target=js+dts"
// @generated from file scraper/v1/scraper.proto (package scraper.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {proto3} from "@bufbuild/protobuf";

/**
 * @generated from message scraper.v1.ScrapeRequest
 */
export const ScrapeRequest = proto3.makeMessageType(
  "scraper.v1.ScrapeRequest",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message scraper.v1.ScrapeResponse
 */
export const ScrapeResponse = proto3.makeMessageType(
  "scraper.v1.ScrapeResponse",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

