// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=js+dts"
// @generated from file scraper/v1/scraper.proto (package scraper.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {ScrapeRequest, ScrapeResponse} from "./scraper_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service scraper.v1.ScraperService
 */
export const ScraperService = {
  typeName: "scraper.v1.ScraperService",
  methods: {
    /**
     * @generated from rpc scraper.v1.ScraperService.Scrape
     */
    scrape: {
      name: "Scrape",
      I: ScrapeRequest,
      O: ScrapeResponse,
      kind: MethodKind.Unary,
    },
  }
};

